config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :guitars
  root 'guitars#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/guitar.rb
# frozen_string_literal: true

class Guitar < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/guitars_controller.rb
# frozen_string_literal: true

class GuitarsController < ApplicationController
  def index
    @guitars = Guitar.all
  end

  def new
    @guitar = Guitar.new
  end

  def create
    @guitar = Guitar.new(guitar_params)

    respond_to do |format|
      if @guitar.save
        format.html do
          redirect_to guitars_url,
                      notice: 'Guitar was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    guitar = Guitar.find(params[:id])
    guitar.destroy

    respond_to do |format|
      format.html { redirect_to guitars_url, notice: 'Guitar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def guitar_params
    params.require(:guitar).permit(:model, :year, :is_available)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/guitars_helper.rb
# frozen_string_literal: true

module GuitarsHelper
end

app/views/guitars/_form.html.erb
<%= form_with(model: guitar) do |form| %>
  <% if guitar.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(guitar.errors.count, "error") %> prohibited this guitar from being saved:</h2>

      <ul>
        <% guitar.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :is_available, style: "display: block" %>
    <%= form.check_box :is_available %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/guitars/_guitar.html.erb
<div id="<%= dom_id guitar %>">
  <p>
    <strong>Model:</strong>
    <%= guitar.model %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= guitar.year %>
  </p>

  <p>
    <strong>Is available:</strong>
    <%= guitar.is_available %>
  </p>

</div>

app/views/guitars/edit.html.erb
<h1>Editing guitar</h1>

<%= render "form", guitar: @guitar %>

<br>

<div>
  <%= link_to "Show this guitar", @guitar %> |
  <%= link_to "Back to guitars", guitars_path %>
</div>

app/views/guitars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Guitars</h1>

<div id="guitars">
  <% @guitars.each do |guitar| %>
    <%= render guitar %>
    <p>
      <%= link_to "Show this guitar", guitar %>
      <%= button_to "Destroy this guitar", guitar, method: :delete %>
    </p>
  <% end %>
</div>

<%= link_to "New guitar", new_guitar_path %>

app/views/guitars/new.html.erb
<h1>New guitar</h1>

<%= render "form", guitar: @guitar %>

<br>

<div>
  <%= link_to "Back to guitars", guitars_path %>
</div>

app/views/guitars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @guitar %>

<div>
  <%= link_to "Edit this guitar", edit_guitar_path(@guitar) %> |
  <%= link_to "Back to guitars", guitars_path %>

  <%= button_to "Destroy this guitar", @guitar, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstrumentStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>